settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: yukpiz.github.io
  path: .
  watcher:
    extensions:
    - html
    - css
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
